server:
  port: 8089

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test  # 무시됨, Testcontainers에서 override됨
#    username: test
#    password: test
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/myapp?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: app
    password: app1234

  data:
    redis:
      host: 127.0.0.1   # A안: 호스트 6379 → 컨테이너 6379
      port: 6379
      password: redis1234

  jpa:
    hibernate:
      ddl-auto: update  # dev: update / prod: validate or none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---


spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://hh_mysql:3306/myapp?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: app
    password: app1234
  data:
    redis:
      host: hh_redis
      port: 6379
      password: redis1234